name: Test Actions
on: 
  push:
  watch:
    types: [started]

jobs:
  one:
    runs-on: ubuntu-16.04
    if: startsWith(github.ref,'refs/tags/')
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_REF: ${{github.ref}}
        run: #echo "$GITHUB_CONTEXT"
          echo "$GITHUB_REF"
