name: Test Actions
on: 
  push:
  watch:
    types: [started]

jobs:
  one:
    runs-on: ubuntu-latest
#    if: startsWith(github.ref,'refs/tags/v')
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_REF: ${{github.ref}}
        run: #echo "$GITHUB_CONTEXT"
          echo "${GITHUB_REF##*refs/heads/}"
