name: Test Actions
on:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  watch:
    types: [started]

jobs:
  one:
    runs-on: ubuntu-latest
    env:
      ttt: hhhh
    steps:
      - run: export rtime=`date "+%Y-%m-%d-%H%M"`
      - name : 打包发布
        run: echo ${rtime}
