name: Test Actions
on:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  watch:
    types: [started]

jobs:
  one:
    runs-on: ubuntu-latest
    env:
      ttt: hhhh
    steps:
      - name : 打包发布
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: Padavan-${date "+%Y-%m-%d-%H%M"}
          path: /opt
