name: Test Actions
on:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  watch:
    types: [started]

jobs:
  one:
    runs-on: ubuntu-latest
    env:
      rtime: $(date "+%Y-%m-%d-%H%M")
    steps:
      - name : 打包发布
        run: echo ${rtime}
